INSERT INTO 
`question`(`question_code`, `question_text`) VALUES 
('Q1', "Who are the members of this household starting from the HH head?"),
('Q2', "What is __'s relationship to HH head?"),
('Q3', "What is __ male or female?"),
('Q4', "How old is __ of his/her last birthday?"),
('Q5', "When was __ born?"),
('Q6', "Where was __ born?"),
('Q7', "Is __ a Filipino? if not, what is __'s nationality?"),
('Q8', "What is __'s current marital status?"),
('Q9', "What is the religion of __?"),
('Q10', "What is __'s ethnicity or is __ a Tagalog, Bicolano, Bisaya, etc?"),
('Q11', "What is the highest education completed by __?"),
('Q12', "Is __ currently enrolled?"),
('Q13', "What type of school is __ on?"),
('Q14', "In waht barangau and city/municipality is __ currently attending school?"),
('Q15',"How much is __'s monthly income?"),
('Q16',"What is the major source of __'s income?"),
('Q17',"What is the status of __'s word/business"),
('Q18',"in what barangay and city/municipality is __'s work/business located?"),
('Q19',"Where was __ delivered?"),
('Q20',"Who attended in the delivery of __?"),
('Q21',"What is the last vaccine received by __?"),
('Q22',"How many pregnancies does __ had? How many child/ren are still living?"),
('Q23',"What family planning method does __ and partner currently use?"),
('Q24',"If using FP, where did they obtain the FP method?"),
('Q25',"Does __ and partner intend to use FP method? If yes, what method? if no, why not?"),
('Q26',"What is the primary health insurance __ have?"),
('Q27',"What facility did __ visited in the past 12 months?"),
('Q28',"What is the reason for the visit in health facility"),
('Q29',"Is there a member of the HH that has any disability? What is the disability"),
('Q30',"Is there a member of the HH that is a solo parent? is he/she registered?"),
('Q31',"Is __ a registered senior citizen?"),
('Q32',"In what barangay is __ a registered voter?"),
('Q33',"In what barangay and city/municipality did __ reside five years ago?"),
('Q34',"In what barangay and city/municipality did __ reside six months ago?"),
('Q35',"How long is __ been stating in thi barangay?"),
('Q36',"Indicate if Non-migrant, Migrant or Transient"),
('Q37',"When did __ transfer in this barangay?"),
('Q38A',"What are the reason/s why __ left his/her previous residence?"),
('Q38B',"What are the reason/s why __ left his/her previous residence?"),
('Q38C',"What are the reason/s why __ left his/her previous residence?"),
('Q39',"Does __ plan to return to previous residence? When?"),
('Q40A',"What are the reason/s why __ tranferred in this barangay?"),
('Q40B',"What are the reason/s why __ tranferred in this barangay?"),
('Q40C',"What are the reason/s why __ tranferred in this barangay?"),
('Q41',"Until when does __ intend to stay in this barangay?"),
('Q42A',"Does __ have a valid CTC"),
('Q42B',"Was the CTC issued in this barangay?"),
('Q43',"What type of skills development training is __ interest to join in?"),
('Q44',"What type of skills do you have?"),
('Q45',"Do you own or amortize this housing unit occupied by your household or do you rent it, do you occupy it rent-free with consent of owner or rent-free without consent of owner?"),
('Q46',"Do you own or amortize this lot occupied by your house hold or do you rent it, do you occupy it rent-free with consent of owner or rent-free without consent of owner?"),
('Q47',"What type of fuel does this household use for lighting?"),
('Q48',"What kind of fuel does this household use most of the time for cooking?"),
('Q49',"What is the household’s main source of drinking water?"),
('Q50A',"How does your household usually dispose of your kitchen garbage such as leftover food, peeling of fruits and vegetables, fish and chicken entrails, and others?"),
('Q50B',"Do you segregate your garbage?"),
('Q51'," What type of toilet facility does this household use?"),
('Q52',"Type of building/house"),
('Q53',"Construction materials of the outer wall"),
('Q54',"Do you have any female HH member who died in the past 12 months? How old is she and what is the cause of her death?"),
('Q55',"Do you have a child HH member below 5 years old who died in the past 12 months? How old is she/he? What is the cause of her/his death?"),
('Q56',"What are the common diseases that causes death in this barangay?"),
('Q57',"What do you think are the primary needs of this barangay?"),
('Q58',"Where does your household intend to stay five years from now?")